openapi: 3.1.0
info:
  title: Shopping API
  version: '1.0'
  description: 'Acme Pet Shop''s Shopping API allows consumers browse and search for pets. Users can find pets by category, tag and other criteria. '
  summary: 'Acme Pet Shop''s Shopping API '
  contact:
    name: John Smith
    url: acmepetshop.co.uk
    email: support@acmepetshop.co.uk
  termsOfService: acmepetshop.co.uk/terms
servers:
  - url: 'http://localhost:3000'
paths:
  /pets:
    get:
      summary: List pets in the store.
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  pets:
                    type: array
                    items:
                      $ref: '#/components/schemas/Pet'
                required:
                  - pets
              examples: {}
      operationId: get-pets
      description: 'List pets in the store. By default results are sorted by the date added to store, most recent pets first.'
      x-internal: false
components:
  schemas:
    Pet:
      title: Pet
      x-stoplight:
        id: 7mqnrn3ta9g0l
      type: object
      description: A pet for sale in the Acme Pet Shop.
      examples:
        '0':
          id: 3cd222e7-c3bf-4b9e-a350-c1db60bd6cb4
          name: Max
          category:
            id: string
          tag: GermanShepherd
          imageUrl: /images/max
          dateAdded: '2022-04-12'
          likes: 5
      properties:
        id:
          type: string
          description: The unique identifier for the pet.
        name:
          type: string
          description: |
            The name of the pet.
        category:
          $ref: '#/components/schemas/Pet-Catgory'
        tag:
          type: string
          description: Characterising labels of the pet.
        imageUrl:
          type: string
          description: A link to the pet’s image.
        dateAdded:
          type: string
          description: Date the pet became available in the store.
          format: date
          example: '2022-04-12'
        likes:
          type: integer
          description: Number of users who have clicked the ‘like’ button for this pet.
      required:
        - id
        - name
        - category
        - dateAdded
    Pet-Catgory:
      title: Pet-Catgory
      x-stoplight:
        id: kf0naj13ce82t
      type: object
      properties:
        id:
          type: string
      description: The classification group of a pet.
  securitySchemes:
    api-key-1:
      name: b21b569b-0d38-4c5c-9a8e-b27c4abaa4be
      type: apiKey
      in: header
      description: ''
security:
  - API Key - 1: []
tags:
  - name: search
